"""add role and course enrollment fields

Revision ID: cf660db93a2a
Revises: d87de128377f
Create Date: 2025-09-01 01:15:22.676908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf660db93a2a'
down_revision = 'd87de128377f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_enrollment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('transaction_id', sa.String(length=100), nullable=True))
        batch_op.create_foreign_key('fk_course_enrollment_user_id_user', 'user', ['user_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('role')

    with op.batch_alter_table('course_enrollment', schema=None) as batch_op:
        batch_op.drop_constraint('fk_course_enrollment_user_id_user', type_='foreignkey')
        batch_op.drop_column('transaction_id')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
